package com.cinenova;

import com.cinenova.autenticación.autenticaciónCliente;
import com.cinenova.consultas.añadirPersona;
import com.cinenova.consultas.obtenerClientes;
import com.cinenova.consultas.obtenerEntradas;
import com.cinenova.entidades.Cliente;
import com.cinenova.entidades.Entrada;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * Clase para la ventana principal de la aplicación
 * 
 * @author Juan Carlos Pizarro Alonso, Álvaro Muñoz Fernández
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        alinearVentana();
    }

    public void alinearVentana(){
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaCliente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JLabel();
        LogoCliente = new javax.swing.JLabel();
        ComprarEntradas = new javax.swing.JButton();
        ModificarEntradas = new javax.swing.JButton();
        ListadoEntradas1 = new javax.swing.JScrollPane();
        ListadoEntradasCliente = new javax.swing.JList<>();
        PuntosObtenidos = new javax.swing.JLabel();
        QueDeseaHacer = new javax.swing.JLabel();
        TituloListadoEntradas = new javax.swing.JLabel();
        VentanaRegistro = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        CampoNombre = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        CorreoRegistro = new javax.swing.JLabel();
        CampoCorreoRegistro = new javax.swing.JTextField();
        ContraseñaRegistro = new javax.swing.JLabel();
        CampoContraseñaRegistro = new javax.swing.JPasswordField();
        RegistrarseConfirmar = new javax.swing.JButton();
        BorrarDatosRegistro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        CampoContraseña = new javax.swing.JPasswordField();
        CampoCorreo = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        IniciarSesión = new javax.swing.JButton();
        NoRegistrado = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();
        Separador = new javax.swing.JSeparator();
        EresEmpleado = new javax.swing.JLabel();
        AccesoEmpleados = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Bienvenida.setText("Bienvenida");

        LogoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cinenova_logo.png"))); // NOI18N

        ComprarEntradas.setText("Comprar entradas");

        ModificarEntradas.setText("Modificar entradas");

        ListadoEntradasCliente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListadoEntradas1.setViewportView(ListadoEntradasCliente);

        PuntosObtenidos.setText("Puntos");

        QueDeseaHacer.setText("¿Qué desea hacer?");

        TituloListadoEntradas.setText("Tu listado de entradas compradas:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComprarEntradas)
                    .addComponent(QueDeseaHacer)
                    .addComponent(ModificarEntradas)
                    .addComponent(LogoCliente)
                    .addComponent(PuntosObtenidos))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Bienvenida)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloListadoEntradas)
                            .addComponent(ListadoEntradas1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LogoCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Bienvenida)))
                .addGap(18, 18, 18)
                .addComponent(QueDeseaHacer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(TituloListadoEntradas)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ComprarEntradas)
                        .addGap(31, 31, 31)
                        .addComponent(ModificarEntradas)
                        .addGap(121, 121, 121)
                        .addComponent(PuntosObtenidos))
                    .addComponent(ListadoEntradas1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout VentanaClienteLayout = new javax.swing.GroupLayout(VentanaCliente.getContentPane());
        VentanaCliente.getContentPane().setLayout(VentanaClienteLayout);
        VentanaClienteLayout.setHorizontalGroup(
            VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaClienteLayout.setVerticalGroup(
            VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        Nombre.setText("Nombre:");

        Apellidos.setText("Apellidos:");

        CorreoRegistro.setText("Correo:");

        ContraseñaRegistro.setText("Contraseña:");

        RegistrarseConfirmar.setText("Registrarse");
        RegistrarseConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseConfirmarActionPerformed(evt);
            }
        });

        BorrarDatosRegistro.setText("Borrar datos");
        BorrarDatosRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarDatosRegistroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CorreoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                    .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CampoApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(CampoNombre)
                                    .addComponent(CampoCorreoRegistro)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoContraseñaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(RegistrarseConfirmar)
                        .addGap(40, 40, 40)
                        .addComponent(BorrarDatosRegistro)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Apellidos)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorreoRegistro)
                    .addComponent(CampoCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaRegistro)
                    .addComponent(CampoContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarseConfirmar)
                    .addComponent(BorrarDatosRegistro))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaRegistroLayout = new javax.swing.GroupLayout(VentanaRegistro.getContentPane());
        VentanaRegistro.getContentPane().setLayout(VentanaRegistroLayout);
        VentanaRegistroLayout.setHorizontalGroup(
            VentanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaRegistroLayout.setVerticalGroup(
            VentanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cinenova.png"))); // NOI18N

        Correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Correo.setText("Correo electrónico: ");

        Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña.setText("Contraseña: ");

        IniciarSesión.setText("Iniciar sesión");
        IniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesiónActionPerformed(evt);
            }
        });

        NoRegistrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoRegistrado.setText("¿No está registrado?");

        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });

        EresEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EresEmpleado.setText("¿Eres empleado?");

        AccesoEmpleados.setText("Acceso empleados");
        AccesoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccesoEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EresEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IniciarSesión)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CampoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(CampoCorreo))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(Registrarse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccesoEmpleados)
                            .addComponent(NoRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contraseña)
                    .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(IniciarSesión)
                .addGap(26, 26, 26)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoRegistrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registrarse)
                .addGap(18, 18, 18)
                .addComponent(EresEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccesoEmpleados)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesiónActionPerformed
        String correo = CampoCorreo.getText();
        char[] password = CampoContraseña.getPassword();
        String contrasena = new String(password);
        
        
        if(autenticaciónCliente.esCliente(correo, contrasena)){
            String nombre = "";
            String apellidos = "";
            List<Cliente> clientes = obtenerClientes.obtenerConsulta();
            for(int i = 0; i < clientes.size(); i++){
                if((clientes.get(i).getCorreo().equals(correo)) && (clientes.get(i).getContrasena().equals(contrasena))){
                    nombre = clientes.get(i).getNombre();
                    apellidos = clientes.get(i).getApellidos();
                }
            }
            List<Entrada> entradas = obtenerEntradas.obtenerConsulta();
            List<Entrada> entradasCliente = null;
            for(int i = 0; i < entradas.size(); i++){
                if(entradas.get(i).getCliente().getCorreo().equals(correo)){
                    entradasCliente.add(entradas.get(i));
                }
            }
            DefaultListModel lista = new DefaultListModel<>();
            if(entradasCliente.size() < 1){
                lista.add(0, "No hay entradas");
            }else{
                for (int i = 0; i < entradasCliente.size(); i++) {
                    lista.addElement(entradasCliente.get(i));
                }
                ListadoEntradasCliente.setModel(lista);
            }
            VentanaCliente.pack();
            VentanaCliente.setLocationRelativeTo(null);
            VentanaCliente.setModal(true);
            VentanaCliente.setTitle("Ventana cliente");
            Bienvenida.setText("¡Bienvenid@ " + nombre + " " + apellidos + "!");
            VentanaCliente.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Correo y/o la contraseña incorrectos.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IniciarSesiónActionPerformed

    private void AccesoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccesoEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccesoEmpleadosActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        VentanaRegistro.pack();
        VentanaRegistro.setLocationRelativeTo(null);
        VentanaRegistro.setTitle("Ventana registro");
        VentanaRegistro.setModal(true);
        VentanaRegistro.setVisible(true);
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void RegistrarseConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseConfirmarActionPerformed
        String nombre = CampoNombre.getText();
        String apellidos = CampoApellidos.getText();
        String correo = CampoCorreoRegistro.getText();
        char[] password = CampoContraseñaRegistro.getPassword();
        String contrasena = new String(password);
        if(!autenticaciónCliente.esCliente(correo, contrasena)){
            int row = añadirPersona.añadirCliente(correo, nombre, apellidos, contrasena);
            if(row > 0){
                JOptionPane.showMessageDialog(VentanaRegistro, "Registro completado exitosamente.","Información",JOptionPane.INFORMATION_MESSAGE);
            VentanaCliente.pack();
            VentanaCliente.setLocationRelativeTo(null);
            VentanaCliente.setTitle("Ventana cliente");
            VentanaCliente.setModal(true);
            VentanaCliente.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(VentanaRegistro, "El registro no ha podido realizarse.","Error",JOptionPane.ERROR_MESSAGE);
            }
            
            CampoNombre.setText("");
            CampoApellidos.setText("");
            CampoCorreoRegistro.setText("");
            CampoContraseñaRegistro.setText("");
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Este cliente ya está registrado.","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_RegistrarseConfirmarActionPerformed

    private void BorrarDatosRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarDatosRegistroActionPerformed
        CampoNombre.setText("");
        CampoApellidos.setText("");
        CampoCorreoRegistro.setText("");
        CampoContraseñaRegistro.setText("");
    }//GEN-LAST:event_BorrarDatosRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccesoEmpleados;
    private javax.swing.JLabel Apellidos;
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JButton BorrarDatosRegistro;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JPasswordField CampoContraseñaRegistro;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoCorreoRegistro;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JButton ComprarEntradas;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel ContraseñaRegistro;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel CorreoRegistro;
    private javax.swing.JLabel EresEmpleado;
    private javax.swing.JButton IniciarSesión;
    private javax.swing.JScrollPane ListadoEntradas1;
    private javax.swing.JList<String> ListadoEntradasCliente;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoCliente;
    private javax.swing.JButton ModificarEntradas;
    private javax.swing.JLabel NoRegistrado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel PuntosObtenidos;
    private javax.swing.JLabel QueDeseaHacer;
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton RegistrarseConfirmar;
    private javax.swing.JSeparator Separador;
    private javax.swing.JLabel TituloListadoEntradas;
    private javax.swing.JDialog VentanaCliente;
    private javax.swing.JDialog VentanaRegistro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
