package com.cinenova;

import com.cinenova.autenticación.autenticaciónCliente;
import com.cinenova.consultas.consultasEntrada;
import com.cinenova.consultas.consultasPersona;
import com.cinenova.consultas.consultasSesion;
import com.cinenova.entidades.Cliente;
import com.cinenova.entidades.Entrada;
import com.cinenova.entidades.Persona;
import com.cinenova.entidades.Sesión;
import java.awt.Color;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Clase para la ventana principal de la aplicación
 * 
 * @author Juan Carlos Pizarro Alonso, Álvaro Muñoz Fernández
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        alinearVentana();
    }

    public void alinearVentana(){
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaCliente = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JLabel();
        LogoCliente = new javax.swing.JLabel();
        ComprarEntradasSesiones = new javax.swing.JButton();
        ListadoEntradas1 = new javax.swing.JScrollPane();
        ListadoEntradasCliente = new javax.swing.JList<>();
        PuntosObtenidos = new javax.swing.JLabel();
        QueDeseaHacer = new javax.swing.JLabel();
        TituloListadoEntradas = new javax.swing.JLabel();
        DescargarEntrada = new javax.swing.JButton();
        DevolverEntrada = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        VentanaRegistro = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        CampoNombre = new javax.swing.JTextField();
        Nombre = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        CampoApellidos = new javax.swing.JTextField();
        CorreoRegistro = new javax.swing.JLabel();
        CampoCorreoRegistro = new javax.swing.JTextField();
        ContraseñaRegistro = new javax.swing.JLabel();
        CampoContraseñaRegistro = new javax.swing.JPasswordField();
        RegistrarseConfirmar = new javax.swing.JButton();
        BorrarDatosRegistro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        VentanaSesiones = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        VerSesionesScroll = new javax.swing.JScrollPane();
        VerSesiones = new javax.swing.JTable();
        ComprarEntrada = new javax.swing.JButton();
        SesionSeleccionada = new javax.swing.JLabel();
        filtrarPeliculas = new javax.swing.JComboBox<>();
        filtrarFecha = new javax.swing.JComboBox<>();
        ordenarPrecio = new javax.swing.JComboBox<>();
        VentanaCompraEntrada = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        TituloComprarEntrada = new javax.swing.JLabel();
        NombrePelicula = new javax.swing.JLabel();
        NumeroSala = new javax.swing.JLabel();
        FechaHoraSesion = new javax.swing.JLabel();
        AsientosDisponibles = new javax.swing.JComboBox<>();
        ComprarEntradaAsiento = new javax.swing.JButton();
        PuntosGanadosCompra = new javax.swing.JLabel();
        ValorPelicula = new javax.swing.JLabel();
        ValorSala = new javax.swing.JLabel();
        ValorDiaHora = new javax.swing.JLabel();
        nombreAsientosDisponibles = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nombrePrecioSesion = new javax.swing.JLabel();
        precioSesion = new javax.swing.JLabel();
        VentanaRutaDescarga = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        CampoContraseña = new javax.swing.JPasswordField();
        CampoCorreo = new javax.swing.JTextField();
        Correo = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        IniciarSesión = new javax.swing.JButton();
        NoRegistrado = new javax.swing.JLabel();
        Registrarse = new javax.swing.JButton();
        Separador = new javax.swing.JSeparator();
        EresEmpleado = new javax.swing.JLabel();
        AccesoEmpleados = new javax.swing.JButton();

        VentanaCliente.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                CerrarProgramaAlCerrarVentanaCliente(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        Bienvenida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Bienvenida.setText("Bienvenida");

        LogoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cinenova_logo.png"))); // NOI18N

        ComprarEntradasSesiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComprarEntradasSesiones.setText("Comprar entrada");
        ComprarEntradasSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarEntradasSesionesActionPerformed(evt);
            }
        });

        ListadoEntradasCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ListadoEntradas1.setViewportView(ListadoEntradasCliente);

        PuntosObtenidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PuntosObtenidos.setText("Puntos");

        QueDeseaHacer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        QueDeseaHacer.setText("¿Qué desea hacer?");

        TituloListadoEntradas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TituloListadoEntradas.setText("Tu listado de entradas compradas:");

        DescargarEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescargarEntrada.setText("Descargar entrada");
        DescargarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescargarEntradaActionPerformed(evt);
            }
        });

        DevolverEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DevolverEntrada.setText("Devolver entrada");
        DevolverEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(QueDeseaHacer)
                    .addComponent(LogoCliente)
                    .addComponent(PuntosObtenidos)
                    .addComponent(DescargarEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DevolverEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComprarEntradasSesiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloListadoEntradas)
                            .addComponent(ListadoEntradas1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bienvenida))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LogoCliente))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(Bienvenida)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(QueDeseaHacer)
                    .addComponent(TituloListadoEntradas, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(ComprarEntradasSesiones)
                        .addGap(29, 29, 29)
                        .addComponent(DevolverEntrada)
                        .addGap(34, 34, 34)
                        .addComponent(DescargarEntrada)
                        .addGap(101, 101, 101)
                        .addComponent(PuntosObtenidos))
                    .addComponent(ListadoEntradas1))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout VentanaClienteLayout = new javax.swing.GroupLayout(VentanaCliente.getContentPane());
        VentanaCliente.getContentPane().setLayout(VentanaClienteLayout);
        VentanaClienteLayout.setHorizontalGroup(
            VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaClienteLayout.setVerticalGroup(
            VentanaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        CampoNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Nombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Nombre.setText("Nombre:");

        Apellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Apellidos.setText("Apellidos:");

        CampoApellidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CorreoRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CorreoRegistro.setText("Correo:");

        CampoCorreoRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ContraseñaRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ContraseñaRegistro.setText("Contraseña:");

        CampoContraseñaRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        RegistrarseConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        RegistrarseConfirmar.setText("Registrarse");
        RegistrarseConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseConfirmarActionPerformed(evt);
            }
        });

        BorrarDatosRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        BorrarDatosRegistro.setText("Borrar datos");
        BorrarDatosRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarDatosRegistroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Introduzca los datos para su registro");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ContraseñaRegistro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CorreoRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Apellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(178, 178, 178)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CampoContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(RegistrarseConfirmar)
                                .addGap(40, 40, 40)
                                .addComponent(BorrarDatosRegistro))
                            .addComponent(CampoCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nombre))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Apellidos)
                    .addComponent(CampoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CorreoRegistro)
                    .addComponent(CampoCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraseñaRegistro)
                    .addComponent(CampoContraseñaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarseConfirmar)
                    .addComponent(BorrarDatosRegistro))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaRegistroLayout = new javax.swing.GroupLayout(VentanaRegistro.getContentPane());
        VentanaRegistro.getContentPane().setLayout(VentanaRegistroLayout);
        VentanaRegistroLayout.setHorizontalGroup(
            VentanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaRegistroLayout.setVerticalGroup(
            VentanaRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        VerSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        VerSesionesScroll.setViewportView(VerSesiones);

        ComprarEntrada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComprarEntrada.setText("Comprar entrada");
        ComprarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarEntradaActionPerformed(evt);
            }
        });

        SesionSeleccionada.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SesionSeleccionada.setText("Seleccione una sesión para poder comprar una entrada");

        filtrarPeliculas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filtrarFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarFecha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ordenarPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ordenarPrecio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VerSesionesScroll)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(SesionSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(ComprarEntrada)
                .addGap(106, 106, 106))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(filtrarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(filtrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ordenarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(filtrarPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtrarFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordenarPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(VerSesionesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprarEntrada)
                    .addComponent(SesionSeleccionada))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout VentanaSesionesLayout = new javax.swing.GroupLayout(VentanaSesiones.getContentPane());
        VentanaSesiones.getContentPane().setLayout(VentanaSesionesLayout);
        VentanaSesionesLayout.setHorizontalGroup(
            VentanaSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaSesionesLayout.setVerticalGroup(
            VentanaSesionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        TituloComprarEntrada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TituloComprarEntrada.setText("Comprar entrada");

        NombrePelicula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NombrePelicula.setText("Pelicula:");

        NumeroSala.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NumeroSala.setText("Sala:");

        FechaHoraSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FechaHoraSesion.setText("Día y hora:");

        AsientosDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AsientosDisponibles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ComprarEntradaAsiento.setText("Comprar entrada");
        ComprarEntradaAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarEntradaAsientoActionPerformed(evt);
            }
        });

        PuntosGanadosCompra.setText("¡Por la compra de una entrada recibirás 5 puntos!");

        ValorPelicula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorPelicula.setText("nombre");

        ValorSala.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorSala.setText("numero");

        ValorDiaHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ValorDiaHora.setText("fecha");

        nombreAsientosDisponibles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreAsientosDisponibles.setText("Asientos disponibles:");

        nombrePrecioSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombrePrecioSesion.setText("Precio final:");

        precioSesion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        precioSesion.setText("precio sesion");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ComprarEntradaAsiento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(PuntosGanadosCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(FechaHoraSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NumeroSala, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NombrePelicula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ValorDiaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ValorPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ValorSala, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(nombrePrecioSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))))
                    .addComponent(TituloComprarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(nombreAsientosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AsientosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(TituloComprarEntrada)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrePelicula)
                    .addComponent(ValorPelicula)
                    .addComponent(nombrePrecioSesion)
                    .addComponent(precioSesion))
                .addGap(47, 47, 47)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumeroSala)
                    .addComponent(ValorSala))
                .addGap(51, 51, 51)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FechaHoraSesion)
                    .addComponent(ValorDiaHora))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AsientosDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreAsientosDisponibles))
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComprarEntradaAsiento)
                    .addComponent(PuntosGanadosCompra))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout VentanaCompraEntradaLayout = new javax.swing.GroupLayout(VentanaCompraEntrada.getContentPane());
        VentanaCompraEntrada.getContentPane().setLayout(VentanaCompraEntradaLayout);
        VentanaCompraEntradaLayout.setHorizontalGroup(
            VentanaCompraEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaCompraEntradaLayout.setVerticalGroup(
            VentanaCompraEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VentanaRutaDescarga.setBackground(java.awt.Color.white);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cinenova.png"))); // NOI18N

        Correo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Correo.setText("Correo electrónico: ");

        Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Contraseña.setText("Contraseña: ");

        IniciarSesión.setText("Iniciar sesión");
        IniciarSesión.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniciarSesiónActionPerformed(evt);
            }
        });

        NoRegistrado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        NoRegistrado.setText("¿No está registrado?");

        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });

        EresEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        EresEmpleado.setText("¿Eres empleado?");

        AccesoEmpleados.setText("Acceso empleados");
        AccesoEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccesoEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(EresEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IniciarSesión)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CampoContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(CampoCorreo))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(Registrarse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccesoEmpleados)
                            .addComponent(NoRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(CampoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contraseña)
                    .addComponent(CampoContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(IniciarSesión)
                .addGap(26, 26, 26)
                .addComponent(Separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NoRegistrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Registrarse)
                .addGap(18, 18, 18)
                .addComponent(EresEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AccesoEmpleados)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesiónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesiónActionPerformed
        String correo = CampoCorreo.getText();
        char[] password = CampoContraseña.getPassword();
        String contrasena = new String(password);
        
        if(autenticaciónCliente.esCliente(correo, contrasena)){
            Cliente cliente = Persona.iniciarSesión(correo);
            String nombre = cliente.getNombre();
            String apellidos = cliente.getApellidos();
            int puntos = cliente.getPuntosGanados();
            List<Entrada> entradasCliente = cliente.verEntradasFuturo();
            DefaultListModel lista = new DefaultListModel<>();
            if(entradasCliente.isEmpty()){
                lista.add(0, "No tienes entradas compradas");
            }else{
                for (int i = 0; i < entradasCliente.size(); i++) {
                       lista.addElement(entradasCliente.get(i)); 
                }
                ListadoEntradasCliente.setModel(lista);
            }
            VentanaCliente.pack();
            VentanaCliente.setLocationRelativeTo(null);
            VentanaCliente.setModal(false);
            VentanaCliente.setTitle("Ventana cliente");
            Bienvenida.setText("¡Bienvenid@ " + nombre + " " + apellidos + "!");
            PuntosObtenidos.setText("Tienes acumulados " + puntos + " puntos.");
            VentanaCliente.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(jPanel1, "Correo y/o la contraseña incorrectos.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_IniciarSesiónActionPerformed

    private void AccesoEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccesoEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AccesoEmpleadosActionPerformed

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        VentanaRegistro.pack();
        VentanaRegistro.setLocationRelativeTo(null);
        VentanaRegistro.setTitle("Ventana registro");
        VentanaRegistro.setModal(true);
        VentanaRegistro.setVisible(true);
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void RegistrarseConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseConfirmarActionPerformed
        String nombre = CampoNombre.getText();
        String apellidos = CampoApellidos.getText();
        String correo = CampoCorreoRegistro.getText();
        char[] password = CampoContraseñaRegistro.getPassword();
        String contrasena = new String(password);
        if (!(correo.contains("@") && correo.contains("."))) {
            JOptionPane.showMessageDialog(VentanaRegistro, "El correo debe contener @ y punto.","Correo no válido",JOptionPane.ERROR_MESSAGE);
        }else if(!autenticaciónCliente.esCliente(correo, contrasena)){
            int row = consultasPersona.añadirCliente(correo, nombre, apellidos, contrasena);
            if(row > 0){
                JOptionPane.showMessageDialog(VentanaRegistro, "Registro completado exitosamente.","Información",JOptionPane.INFORMATION_MESSAGE);
                consultasPersona.obtenerClientes();
                Cliente cliente = Persona.iniciarSesión(correo);
                String nombreMostrar = cliente.getNombre();
                String apellidosMostrar = cliente.getApellidos();
                int puntos = cliente.getPuntosGanados();
                List<Entrada> entradasCliente = cliente.verEntradasFuturo();
                DefaultListModel lista = new DefaultListModel<>();
                if(entradasCliente.isEmpty()){
                    lista.addElement("No tienes entradas compradas");
                }else{
                    for (int i = 0; i < entradasCliente.size(); i++) {
                           lista.addElement(entradasCliente.get(i)); 

                    }
                    ListadoEntradasCliente.setModel(lista);
                    

            }
            VentanaRegistro.dispose();
            VentanaCliente.pack();
            VentanaCliente.setLocationRelativeTo(null);
            VentanaCliente.setTitle("Área de cliente");
            Bienvenida.setText("¡Bienvenid@ " + nombreMostrar + " " + apellidosMostrar + "!");
            PuntosObtenidos.setText("Tienes acumulados " + puntos + " puntos.");
            VentanaCliente.setModal(false);
            VentanaCliente.setVisible(true);
            this.dispose();
            }else{
                JOptionPane.showMessageDialog(VentanaRegistro, "El registro no ha podido realizarse.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(VentanaRegistro, "Este cliente ya está registrado.","Error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_RegistrarseConfirmarActionPerformed

    private void BorrarDatosRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarDatosRegistroActionPerformed
        CampoNombre.setText("");
        CampoApellidos.setText("");
        CampoCorreoRegistro.setText("");
        CampoContraseñaRegistro.setText("");
    }//GEN-LAST:event_BorrarDatosRegistroActionPerformed

    private void DevolverEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverEntradaActionPerformed
        int indice = ListadoEntradasCliente.getSelectedIndex();
        String correo = "";
        if(CampoCorreo.getText().isEmpty() || CampoCorreo.getText().isBlank()){
            System.out.println(CampoCorreoRegistro.getText());
            System.out.println(CampoCorreo.getText());
            correo = CampoCorreoRegistro.getText();
        }else{
            correo = CampoCorreo.getText();
        }
        consultasPersona.obtenerClientes();
        Cliente cliente = Persona.iniciarSesión(correo);
        if(indice == -1){
            JOptionPane.showMessageDialog(VentanaCliente, "Seleccione la entrada que desea devolver.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            boolean exito = cliente.devolverEntrada(cliente.verEntradasFuturo().get(indice));
            if(exito){
                JOptionPane.showMessageDialog(VentanaCliente, "La entrada ha sido devuelta con éxito.","Entrada devuelta",JOptionPane.INFORMATION_MESSAGE);
                List<Entrada> entradas = consultasEntrada.obtenerConsulta();
                    List<Entrada> entradasCliente = cliente.verEntradasFuturo();
                    DefaultListModel lista = new DefaultListModel<>();
                    if(entradasCliente.isEmpty()){
                        lista.addElement("No tienes entradas compradas");
                    }else{
                        Date hoy = new Date();
                        for (int i = 0; i < entradasCliente.size(); i++) {
                            if(entradasCliente.get(i).getSesion().getFechaHora().after(hoy)){
                               lista.addElement(entradasCliente.get(i)); 
                            }

                        }

                    }
                    ListadoEntradasCliente.setModel(lista);
            }else{
                JOptionPane.showMessageDialog(VentanaCliente, "La entrada no ha podido ser devuelta.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_DevolverEntradaActionPerformed

    private void DescargarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescargarEntradaActionPerformed
        int indice = ListadoEntradasCliente.getSelectedIndex();
        String correo = "";
        if(CampoCorreo.getText().isEmpty() || CampoCorreo.getText().isBlank()){
            System.out.println(CampoCorreoRegistro.getText());
            System.out.println(CampoCorreo.getText());
            correo = CampoCorreoRegistro.getText();
        }else{
            correo = CampoCorreo.getText();
        }
        consultasPersona.obtenerClientes();
        Cliente cliente = Persona.iniciarSesión(correo);
        if(indice == -1){
            JOptionPane.showMessageDialog(VentanaCliente, "Seleccione la entrada que desea descargar.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            boolean descargada = false;
            VentanaRutaDescarga.setDialogTitle("Guardar entrada descargada");
            VentanaRutaDescarga.setSelectedFile(new File("entrada_descargada.txt"));

            int userSelection = VentanaRutaDescarga.showSaveDialog(null);

            if (userSelection == JFileChooser.APPROVE_OPTION) {
                File archivo = VentanaRutaDescarga.getSelectedFile();
                descargada = cliente.descargarEntrada(cliente.verEntradasFuturo().get(indice), archivo);
            }

            if(descargada){
                JOptionPane.showMessageDialog(VentanaCliente, "La entrada se ha descargado.","Entrada descargada",JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(VentanaCliente, "La entrada no se ha podido descargar.","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_DescargarEntradaActionPerformed

    private void ComprarEntradasSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarEntradasSesionesActionPerformed
        VentanaSesiones.pack();
        VentanaSesiones.setLocationRelativeTo(null);
        VentanaSesiones.setTitle("Sesiones disponibles");
        VentanaSesiones.setModal(true);
        String correo = "";
        if(CampoCorreo.getText().isEmpty() || CampoCorreo.getText().isBlank()){
            System.out.println(CampoCorreoRegistro.getText());
            System.out.println(CampoCorreo.getText());
            correo = CampoCorreoRegistro.getText();
        }else{
            correo = CampoCorreo.getText();
        }
        consultasPersona.obtenerClientes();
        Cliente cliente = Persona.iniciarSesión(correo);
        List<Sesión> sesiones = cliente.verSesionesFuturo();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        String[] columnas = {"Titulo", "Sala", "Fecha/Hora", "Precio", "Asientos disponibles"};
        DefaultTableModel tabla = new DefaultTableModel(columnas, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // desactiva edición de todas las celdas
            }
        };
        Map<Integer, Integer> entradasVendidas = consultasEntrada.obtenerEntradasCompradasPorSala();
              
        if(sesiones.isEmpty()){
            JOptionPane.showMessageDialog(VentanaSesiones, "No se han encontrado entradas a la venta","Información",JOptionPane.INFORMATION_MESSAGE);
        }else{
            for (int i = 0; i < sesiones.size(); i++) {
                    int numeroSala = sesiones.get(i).getSala().getNumero();
                    int capacidad = sesiones.get(i).getSala().getCapacidad();
                    int vendidas = entradasVendidas.getOrDefault(numeroSala, 0);
                    int asientosDisponibles = capacidad - vendidas;
                    String asientosDisponiblesTotal = String.valueOf(asientosDisponibles) + "/" + String.valueOf(capacidad);
                    Object[] fila = {
                        sesiones.get(i).getPelicula().getTitulo(),
                        sesiones.get(i).getSala().getNumero(),
                        formato.format(sesiones.get(i).getFechaHora()),
                        sesiones.get(i).getPrecio(),
                        asientosDisponiblesTotal
                    };
                    tabla.addRow(fila);
                }
            }
            VerSesiones.setModel(tabla);
            VerSesiones.setEnabled(true);
            VerSesiones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            VentanaSesiones.setVisible(true);        
    }//GEN-LAST:event_ComprarEntradasSesionesActionPerformed

    private void ComprarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarEntradaActionPerformed
        VentanaCompraEntrada.pack();
        VentanaCompraEntrada.setLocationRelativeTo(null);
        VentanaCompraEntrada.setTitle("Comprar entrada");
        VentanaCompraEntrada.setModal(true);
        AsientosDisponibles.removeAllItems();
        int sesionSeleccionada = VerSesiones.getSelectedRow();
        if(sesionSeleccionada == -1){
            JOptionPane.showMessageDialog(VentanaSesiones, "Seleccione la sesión para comprar la entrada.","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String correo = "";
            if(CampoCorreo.getText().isEmpty() || CampoCorreo.getText().isBlank()){
                System.out.println(CampoCorreoRegistro.getText());
                System.out.println(CampoCorreo.getText());
                correo = CampoCorreoRegistro.getText();
            }else{
                correo = CampoCorreo.getText();
            }
            consultasPersona.obtenerClientes();
            Cliente cliente = Persona.iniciarSesión(correo);
            List<Sesión> sesiones = cliente.verSesionesFuturo();
            Sesión sesión = null;
            SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
            for(int i = 0; i < sesiones.size(); i++){
                if(i == sesionSeleccionada){
                    sesión = sesiones.get(i);
                }
            }
            Entrada entrada = new Entrada(0, cliente, sesión, sesión.getPrecio());
            ValorPelicula.setText(sesión.getPelicula().getTitulo());
            ValorSala.setText(String.valueOf(sesión.getSala().getNumero()));
            ValorDiaHora.setText(formato.format(sesión.getFechaHora()));
            precioSesion.setText(String.valueOf(sesión.getPrecio()));
            entrada.setPrecioFinal(sesión.getPrecio());
            precioSesion.setText(String.valueOf(entrada.getPrecioFinal()));
            if(Double.valueOf(precioSesion.getText()) != sesión.getPrecio()){
                precioSesion.setForeground(Color.red);
            }
            int capacidad = sesión.getSala().getCapacidad();
            List<Integer> obtenerEntrada;
            List<Integer> asientosOcupados = consultasEntrada.obtenerAsientosOcupadosDeSala(sesión.getSala().getNumero());
            Set<Integer> ocupadosSet = new HashSet<>(asientosOcupados);
            for (int i = 1; i <= capacidad; i++) {
                if (!ocupadosSet.contains(i)) {
                    AsientosDisponibles.addItem(String.valueOf(i));
                }
            }
        }
        
        VentanaCompraEntrada.setVisible(true);
    }//GEN-LAST:event_ComprarEntradaActionPerformed

    private void ComprarEntradaAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarEntradaAsientoActionPerformed
        int sesionSeleccionada = VerSesiones.getSelectedRow();
        Sesión sesión = null;
        String correo = "";
        if(CampoCorreo.getText().isEmpty() || CampoCorreo.getText().isBlank()){
            System.out.println(CampoCorreoRegistro.getText());
            System.out.println(CampoCorreo.getText());
            correo = CampoCorreoRegistro.getText();
        }else{
            correo = CampoCorreo.getText();
        }
        consultasPersona.obtenerClientes();
        Cliente cliente = Persona.iniciarSesión(correo);
        List<Sesión> sesiones = cliente.verSesionesFuturo();
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        for(int i = 0; i < sesiones.size(); i++){
            if(i == sesionSeleccionada){
                sesión = sesiones.get(i);
            }
        }
        int asiento = Integer.parseInt(AsientosDisponibles.getSelectedItem().toString());
        Entrada entrada = new Entrada(asiento, cliente, sesión, sesión.getPrecio());
        entrada.setPrecioFinal(entrada.getSesion().getPrecio());
        boolean exito = cliente.comprarEntrada(entrada);
        if(exito){
            cliente.setPuntosGanados(cliente.getPuntosGanados() + 5);
            consultasPersona.actualizarPuntos(cliente);
            JOptionPane.showMessageDialog(VentanaCompraEntrada, "Entrada comprada con éxito.","Entrada comprada",JOptionPane.INFORMATION_MESSAGE);
            List<Entrada> entradas = consultasEntrada.obtenerConsulta();
                List<Entrada> entradasCliente = cliente.verEntradasFuturo();
                DefaultListModel lista = new DefaultListModel<>();
                if(entradasCliente.isEmpty()){
                    lista.addElement("No tienes entradas compradas");
                }else{
                    Date hoy = new Date();
                    for (int i = 0; i < entradasCliente.size(); i++) {
                        if(entradasCliente.get(i).getSesion().getFechaHora().after(hoy)){
                           lista.addElement(entradasCliente.get(i)); 
                        }

                    }
                    
                }
                ListadoEntradasCliente.setModel(lista);
                PuntosObtenidos.setText("Tienes acumulados " + cliente.getPuntosGanados() + " puntos.");
                VentanaCompraEntrada.dispose();
        }else{
            JOptionPane.showMessageDialog(VentanaCompraEntrada, "No se ha podido comprar la entrada.","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ComprarEntradaAsientoActionPerformed

    private void CerrarProgramaAlCerrarVentanaCliente(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_CerrarProgramaAlCerrarVentanaCliente
        System.exit(0);
    }//GEN-LAST:event_CerrarProgramaAlCerrarVentanaCliente

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccesoEmpleados;
    private javax.swing.JLabel Apellidos;
    private javax.swing.JComboBox<String> AsientosDisponibles;
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JButton BorrarDatosRegistro;
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JPasswordField CampoContraseña;
    private javax.swing.JPasswordField CampoContraseñaRegistro;
    private javax.swing.JTextField CampoCorreo;
    private javax.swing.JTextField CampoCorreoRegistro;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JButton ComprarEntrada;
    private javax.swing.JButton ComprarEntradaAsiento;
    private javax.swing.JButton ComprarEntradasSesiones;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel ContraseñaRegistro;
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel CorreoRegistro;
    private javax.swing.JButton DescargarEntrada;
    private javax.swing.JButton DevolverEntrada;
    private javax.swing.JLabel EresEmpleado;
    private javax.swing.JLabel FechaHoraSesion;
    private javax.swing.JButton IniciarSesión;
    private javax.swing.JScrollPane ListadoEntradas1;
    private javax.swing.JList<String> ListadoEntradasCliente;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel LogoCliente;
    private javax.swing.JLabel NoRegistrado;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel NombrePelicula;
    private javax.swing.JLabel NumeroSala;
    private javax.swing.JLabel PuntosGanadosCompra;
    private javax.swing.JLabel PuntosObtenidos;
    private javax.swing.JLabel QueDeseaHacer;
    private javax.swing.JButton Registrarse;
    private javax.swing.JButton RegistrarseConfirmar;
    private javax.swing.JSeparator Separador;
    private javax.swing.JLabel SesionSeleccionada;
    private javax.swing.JLabel TituloComprarEntrada;
    private javax.swing.JLabel TituloListadoEntradas;
    private javax.swing.JLabel ValorDiaHora;
    private javax.swing.JLabel ValorPelicula;
    private javax.swing.JLabel ValorSala;
    private javax.swing.JDialog VentanaCliente;
    private javax.swing.JDialog VentanaCompraEntrada;
    private javax.swing.JDialog VentanaRegistro;
    private javax.swing.JFileChooser VentanaRutaDescarga;
    private javax.swing.JDialog VentanaSesiones;
    private javax.swing.JTable VerSesiones;
    private javax.swing.JScrollPane VerSesionesScroll;
    private javax.swing.JComboBox<String> filtrarFecha;
    private javax.swing.JComboBox<String> filtrarPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nombreAsientosDisponibles;
    private javax.swing.JLabel nombrePrecioSesion;
    private javax.swing.JComboBox<String> ordenarPrecio;
    private javax.swing.JLabel precioSesion;
    // End of variables declaration//GEN-END:variables
}
